; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.9"

; Modules
projects[admin_menu][subdir] = "sites/all/modules/contrib/admin_menu"
projects[admin_menu][version] = "3.0-rc1"

projects[auto_nodetitle][subdir] = "sites/all/modules/contrib/auto_nodetitle"
projects[auto_nodetitle][version] = "1.0"

projects[backup_migrate][subdir] = "sites/all/modules/contrib/backup_migrate"
projects[backup_migrate][version] = "2.2"

projects[ctools][subdir] = "sites/all/modules/contrib/ctools"
projects[ctools][version] = "1.0-rc1"

projects[context][subdir] = "sites/all/modules/contrib/context"
projects[context][version] = "3.0-beta2"

projects[devel][subdir] = "sites/all/modules/contrib/devel"
projects[devel][version] = "1.2"

projects[globalredirect][subdir] = "sites/all/modules/contrib/globalredirect"
projects[globalredirect][version] = "1.3"

projects[pathauto][subdir] = "sites/all/modules/contrib/pathauto"
projects[pathauto][version] = "1.0"

projects[token][subdir] = "sites/all/modules/contrib/token"
projects[token][version] = "1.0-beta7"

; Themes
projects[adaptivetheme][subdir] = "sites/all/themes/contrib/adaptivetheme"
projects[adaptivetheme][version] = "2.1"

projects[corolla][subdir] = "sites/all/themes/contrib/corolla"
projects[corolla][version] = "2.2"

projects[footheme][subdir] = "sites/all/themes"
projects[footheme][version] = "2.0"

